################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/StarBright/Common/Time \
src/StarBright/Common \
src/StarBright/ThirdParty/cereal/build/CMakeFiles/3.6.2/CompilerIdC \
src/StarBright/ThirdParty/cereal/build/CMakeFiles/3.6.2/CompilerIdCXX \
src/StarBright/ThirdParty/cereal/build/CMakeFiles \
src/StarBright/ThirdParty/cereal/sandbox \
src/StarBright/ThirdParty/cereal/sandbox/sandbox_shared_lib \
src/StarBright/ThirdParty/cereal/unittests \
src/StarBright/ThirdParty/cereal/vs2013/unittests \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_aead/aes256gcm/aesni \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_aead/xchacha20poly1305/sodium \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_auth \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_auth/hmacsha256 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_auth/hmacsha512 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_auth/hmacsha512256 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_box \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_box/curve25519xchacha20poly1305 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_box/curve25519xsalsa20poly1305 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_core/curve25519/ref10 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_core/hchacha20 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_core/hsalsa20 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_core/hsalsa20/ref2 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_core/salsa/ref \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_generichash/blake2b \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_generichash/blake2b/ref \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_generichash \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_hash \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_hash/sha256/cp \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_hash/sha256 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_hash/sha512/cp \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_hash/sha512 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_kdf/blake2b \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_kdf \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_kx \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_onetimeauth \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_onetimeauth/poly1305 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_onetimeauth/poly1305/sse2 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_pwhash/argon2 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_pwhash \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/sse \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_scalarmult \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_scalarmult/curve25519/donna_c64 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_scalarmult/curve25519/sandy2x \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_scalarmult/curve25519 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_secretbox \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_secretbox/xchacha20poly1305 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_secretbox/xsalsa20poly1305 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_secretstream/xchacha20poly1305 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_shorthash \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_shorthash/siphash24/ref \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_shorthash/siphash24 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_sign \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_sign/ed25519/ref10 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_sign/ed25519 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/chacha20/dolbeau \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/chacha20/ref \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/chacha20 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa20/ref \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa20 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa20/xmm6 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa20/xmm6int \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa2012/ref \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa2012 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa208/ref \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa208 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/xchacha20 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_stream/xsalsa20 \
src/StarBright/ThirdParty/libsodium/src/libsodium/crypto_verify/sodium \
src/StarBright/ThirdParty/libsodium/src/libsodium/randombytes/nativeclient \
src/StarBright/ThirdParty/libsodium/src/libsodium/randombytes \
src/StarBright/ThirdParty/libsodium/src/libsodium/randombytes/salsa20 \
src/StarBright/ThirdParty/libsodium/src/libsodium/randombytes/sysrandom \
src/StarBright/ThirdParty/libsodium/src/libsodium/sodium \
src/StarBright/ThirdParty/libsodium/test/default \
src/StarBright/ThirdParty/nanomsg/demo \
src/StarBright/ThirdParty/nanomsg/perf \
src/StarBright/ThirdParty/nanomsg/src/aio \
src/StarBright/ThirdParty/nanomsg/src/core \
src/StarBright/ThirdParty/nanomsg/src/devices \
src/StarBright/ThirdParty/nanomsg/src/protocols/bus \
src/StarBright/ThirdParty/nanomsg/src/protocols/pair \
src/StarBright/ThirdParty/nanomsg/src/protocols/pipeline \
src/StarBright/ThirdParty/nanomsg/src/protocols/pubsub \
src/StarBright/ThirdParty/nanomsg/src/protocols/reqrep \
src/StarBright/ThirdParty/nanomsg/src/protocols/survey \
src/StarBright/ThirdParty/nanomsg/src/protocols/utils \
src/StarBright/ThirdParty/nanomsg/src/transports/inproc \
src/StarBright/ThirdParty/nanomsg/src/transports/ipc \
src/StarBright/ThirdParty/nanomsg/src/transports/tcp \
src/StarBright/ThirdParty/nanomsg/src/transports/utils \
src/StarBright/ThirdParty/nanomsg/src/transports/ws \
src/StarBright/ThirdParty/nanomsg/src/utils \
src/StarBright/ThirdParty/nanomsg/tests \
src/StarBright/ThirdParty/nanomsg/tools \
src/StarBright/ThirdParty/openssl/apps \
src/StarBright/ThirdParty/openssl/crypto \
src/StarBright/ThirdParty/openssl/crypto/aes \
src/StarBright/ThirdParty/openssl/crypto/aes/asm \
src/StarBright/ThirdParty/openssl/crypto/asn1 \
src/StarBright/ThirdParty/openssl/crypto/async/arch \
src/StarBright/ThirdParty/openssl/crypto/async \
src/StarBright/ThirdParty/openssl/crypto/bf \
src/StarBright/ThirdParty/openssl/crypto/bio \
src/StarBright/ThirdParty/openssl/crypto/blake2 \
src/StarBright/ThirdParty/openssl/crypto/bn/asm \
src/StarBright/ThirdParty/openssl/crypto/bn \
src/StarBright/ThirdParty/openssl/crypto/buffer \
src/StarBright/ThirdParty/openssl/crypto/camellia \
src/StarBright/ThirdParty/openssl/crypto/cast \
src/StarBright/ThirdParty/openssl/crypto/chacha \
src/StarBright/ThirdParty/openssl/crypto/cmac \
src/StarBright/ThirdParty/openssl/crypto/cms \
src/StarBright/ThirdParty/openssl/crypto/comp \
src/StarBright/ThirdParty/openssl/crypto/conf \
src/StarBright/ThirdParty/openssl/crypto/ct \
src/StarBright/ThirdParty/openssl/crypto/des \
src/StarBright/ThirdParty/openssl/crypto/dh \
src/StarBright/ThirdParty/openssl/crypto/dsa \
src/StarBright/ThirdParty/openssl/crypto/dso \
src/StarBright/ThirdParty/openssl/crypto/ec \
src/StarBright/ThirdParty/openssl/crypto/engine \
src/StarBright/ThirdParty/openssl/crypto/err \
src/StarBright/ThirdParty/openssl/crypto/evp \
src/StarBright/ThirdParty/openssl/crypto/hmac \
src/StarBright/ThirdParty/openssl/crypto/idea \
src/StarBright/ThirdParty/openssl/crypto/kdf \
src/StarBright/ThirdParty/openssl/crypto/lhash \
src/StarBright/ThirdParty/openssl/crypto/md2 \
src/StarBright/ThirdParty/openssl/crypto/md4 \
src/StarBright/ThirdParty/openssl/crypto/md5/asm \
src/StarBright/ThirdParty/openssl/crypto/md5 \
src/StarBright/ThirdParty/openssl/crypto/mdc2 \
src/StarBright/ThirdParty/openssl/crypto/modes \
src/StarBright/ThirdParty/openssl/crypto/objects \
src/StarBright/ThirdParty/openssl/crypto/ocsp \
src/StarBright/ThirdParty/openssl/crypto/pem \
src/StarBright/ThirdParty/openssl/crypto/pkcs12 \
src/StarBright/ThirdParty/openssl/crypto/pkcs7 \
src/StarBright/ThirdParty/openssl/crypto/poly1305 \
src/StarBright/ThirdParty/openssl/crypto/rand \
src/StarBright/ThirdParty/openssl/crypto/rc2 \
src/StarBright/ThirdParty/openssl/crypto/rc4 \
src/StarBright/ThirdParty/openssl/crypto/rc5 \
src/StarBright/ThirdParty/openssl/crypto/ripemd \
src/StarBright/ThirdParty/openssl/crypto/rsa \
src/StarBright/ThirdParty/openssl/crypto/seed \
src/StarBright/ThirdParty/openssl/crypto/sha \
src/StarBright/ThirdParty/openssl/crypto/srp \
src/StarBright/ThirdParty/openssl/crypto/stack \
src/StarBright/ThirdParty/openssl/crypto/ts \
src/StarBright/ThirdParty/openssl/crypto/txt_db \
src/StarBright/ThirdParty/openssl/crypto/ui \
src/StarBright/ThirdParty/openssl/crypto/whrlpool \
src/StarBright/ThirdParty/openssl/crypto/x509 \
src/StarBright/ThirdParty/openssl/crypto/x509v3 \
src/StarBright/ThirdParty/openssl/demos/bio \
src/StarBright/ThirdParty/openssl/demos/cms \
src/StarBright/ThirdParty/openssl/demos/evp \
src/StarBright/ThirdParty/openssl/demos/pkcs12 \
src/StarBright/ThirdParty/openssl/demos/smime \
src/StarBright/ThirdParty/openssl/engines/afalg \
src/StarBright/ThirdParty/openssl/engines \
src/StarBright/ThirdParty/openssl/fuzz \
src/StarBright/ThirdParty/openssl/ms \
src/StarBright/ThirdParty/openssl/ssl \
src/StarBright/ThirdParty/openssl/ssl/record \
src/StarBright/ThirdParty/openssl/ssl/statem \
src/StarBright/ThirdParty/openssl/test \
src/StarBright/ThirdParty/poco/CppUnit/WinTestRunner/src \
src/StarBright/ThirdParty/poco/CppUnit/src \
src/StarBright/ThirdParty/poco/Crypto/samples/genrsakey/src \
src/StarBright/ThirdParty/poco/Crypto/src \
src/StarBright/ThirdParty/poco/Crypto/testsuite/src \
src/StarBright/ThirdParty/poco/Data/MySQL/src \
src/StarBright/ThirdParty/poco/Data/MySQL/testsuite/src \
src/StarBright/ThirdParty/poco/Data/ODBC/src \
src/StarBright/ThirdParty/poco/Data/ODBC/testsuite/src \
src/StarBright/ThirdParty/poco/Data/SQLite/src \
src/StarBright/ThirdParty/poco/Data/SQLite/testsuite/src \
src/StarBright/ThirdParty/poco/Data/samples/Binding/src \
src/StarBright/ThirdParty/poco/Data/samples/RecordSet/src \
src/StarBright/ThirdParty/poco/Data/samples/RowFormatter/src \
src/StarBright/ThirdParty/poco/Data/samples/Tuple/src \
src/StarBright/ThirdParty/poco/Data/samples/TypeHandler/src \
src/StarBright/ThirdParty/poco/Data/samples/WebNotifier/src \
src/StarBright/ThirdParty/poco/Data/src \
src/StarBright/ThirdParty/poco/Data/testsuite/src \

