################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/Common \
src/ThirdParty/azmq/doc/examples/actor \
src/ThirdParty/azmq/test/actor \
src/ThirdParty/azmq/test/context_ops \
src/ThirdParty/azmq/test/message \
src/ThirdParty/azmq/test/signal \
src/ThirdParty/azmq/test/socket \
src/ThirdParty/azmq/test/socket_ops \
src/ThirdParty/cereal/build/CMakeFiles/3.6.2/CompilerIdC \
src/ThirdParty/cereal/build/CMakeFiles/3.6.2/CompilerIdCXX \
src/ThirdParty/cereal/build/CMakeFiles \
src/ThirdParty/cereal/sandbox \
src/ThirdParty/cereal/sandbox/sandbox_shared_lib \
src/ThirdParty/cereal/unittests \
src/ThirdParty/cereal/vs2013/unittests \
src/ThirdParty/libsodium/src/libsodium/crypto_aead/aes256gcm/aesni \
src/ThirdParty/libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium \
src/ThirdParty/libsodium/src/libsodium/crypto_aead/xchacha20poly1305/sodium \
src/ThirdParty/libsodium/src/libsodium/crypto_auth \
src/ThirdParty/libsodium/src/libsodium/crypto_auth/hmacsha256 \
src/ThirdParty/libsodium/src/libsodium/crypto_auth/hmacsha512 \
src/ThirdParty/libsodium/src/libsodium/crypto_auth/hmacsha512256 \
src/ThirdParty/libsodium/src/libsodium/crypto_box \
src/ThirdParty/libsodium/src/libsodium/crypto_box/curve25519xchacha20poly1305 \
src/ThirdParty/libsodium/src/libsodium/crypto_box/curve25519xsalsa20poly1305 \
src/ThirdParty/libsodium/src/libsodium/crypto_core/curve25519/ref10 \
src/ThirdParty/libsodium/src/libsodium/crypto_core/hchacha20 \
src/ThirdParty/libsodium/src/libsodium/crypto_core/hsalsa20 \
src/ThirdParty/libsodium/src/libsodium/crypto_core/hsalsa20/ref2 \
src/ThirdParty/libsodium/src/libsodium/crypto_core/salsa/ref \
src/ThirdParty/libsodium/src/libsodium/crypto_generichash/blake2b \
src/ThirdParty/libsodium/src/libsodium/crypto_generichash/blake2b/ref \
src/ThirdParty/libsodium/src/libsodium/crypto_generichash \
src/ThirdParty/libsodium/src/libsodium/crypto_hash \
src/ThirdParty/libsodium/src/libsodium/crypto_hash/sha256/cp \
src/ThirdParty/libsodium/src/libsodium/crypto_hash/sha256 \
src/ThirdParty/libsodium/src/libsodium/crypto_hash/sha512/cp \
src/ThirdParty/libsodium/src/libsodium/crypto_hash/sha512 \
src/ThirdParty/libsodium/src/libsodium/crypto_kdf/blake2b \
src/ThirdParty/libsodium/src/libsodium/crypto_kdf \
src/ThirdParty/libsodium/src/libsodium/crypto_kx \
src/ThirdParty/libsodium/src/libsodium/crypto_onetimeauth \
src/ThirdParty/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna \
src/ThirdParty/libsodium/src/libsodium/crypto_onetimeauth/poly1305 \
src/ThirdParty/libsodium/src/libsodium/crypto_onetimeauth/poly1305/sse2 \
src/ThirdParty/libsodium/src/libsodium/crypto_pwhash/argon2 \
src/ThirdParty/libsodium/src/libsodium/crypto_pwhash \
src/ThirdParty/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256 \
src/ThirdParty/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse \
src/ThirdParty/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/sse \
src/ThirdParty/libsodium/src/libsodium/crypto_scalarmult \
src/ThirdParty/libsodium/src/libsodium/crypto_scalarmult/curve25519/donna_c64 \
src/ThirdParty/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10 \
src/ThirdParty/libsodium/src/libsodium/crypto_scalarmult/curve25519/sandy2x \
src/ThirdParty/libsodium/src/libsodium/crypto_scalarmult/curve25519 \
src/ThirdParty/libsodium/src/libsodium/crypto_secretbox \
src/ThirdParty/libsodium/src/libsodium/crypto_secretbox/xchacha20poly1305 \
src/ThirdParty/libsodium/src/libsodium/crypto_secretbox/xsalsa20poly1305 \
src/ThirdParty/libsodium/src/libsodium/crypto_secretstream/xchacha20poly1305 \
src/ThirdParty/libsodium/src/libsodium/crypto_shorthash \
src/ThirdParty/libsodium/src/libsodium/crypto_shorthash/siphash24/ref \
src/ThirdParty/libsodium/src/libsodium/crypto_shorthash/siphash24 \
src/ThirdParty/libsodium/src/libsodium/crypto_sign \
src/ThirdParty/libsodium/src/libsodium/crypto_sign/ed25519/ref10 \
src/ThirdParty/libsodium/src/libsodium/crypto_sign/ed25519 \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/chacha20/dolbeau \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/chacha20/ref \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/chacha20 \
src/ThirdParty/libsodium/src/libsodium/crypto_stream \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa20/ref \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa20 \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa20/xmm6 \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa20/xmm6int \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa2012/ref \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa2012 \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa208/ref \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/salsa208 \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/xchacha20 \
src/ThirdParty/libsodium/src/libsodium/crypto_stream/xsalsa20 \
src/ThirdParty/libsodium/src/libsodium/crypto_verify/sodium \
src/ThirdParty/libsodium/src/libsodium/randombytes/nativeclient \
src/ThirdParty/libsodium/src/libsodium/randombytes \
src/ThirdParty/libsodium/src/libsodium/randombytes/salsa20 \
src/ThirdParty/libsodium/src/libsodium/randombytes/sysrandom \
src/ThirdParty/libsodium/src/libsodium/sodium \
src/ThirdParty/libsodium/test/default \
src/ThirdParty/nanomsg/demo \
src/ThirdParty/nanomsg/perf \
src/ThirdParty/nanomsg/src/aio \
src/ThirdParty/nanomsg/src/core \
src/ThirdParty/nanomsg/src/devices \
src/ThirdParty/nanomsg/src/protocols/bus \
src/ThirdParty/nanomsg/src/protocols/pair \
src/ThirdParty/nanomsg/src/protocols/pipeline \
src/ThirdParty/nanomsg/src/protocols/pubsub \
src/ThirdParty/nanomsg/src/protocols/reqrep \
src/ThirdParty/nanomsg/src/protocols/survey \
src/ThirdParty/nanomsg/src/protocols/utils \
src/ThirdParty/nanomsg/src/transports/inproc \
src/ThirdParty/nanomsg/src/transports/ipc \
src/ThirdParty/nanomsg/src/transports/tcp \
src/ThirdParty/nanomsg/src/transports/utils \
src/ThirdParty/nanomsg/src/transports/ws \
src/ThirdParty/nanomsg/src/utils \
src/ThirdParty/nanomsg/tests \
src/ThirdParty/nanomsg/tools \
src/ThirdParty/openssl/apps \
src/ThirdParty/openssl/crypto \
src/ThirdParty/openssl/crypto/aes \
src/ThirdParty/openssl/crypto/aes/asm \
src/ThirdParty/openssl/crypto/asn1 \
src/ThirdParty/openssl/crypto/async/arch \
src/ThirdParty/openssl/crypto/async \
src/ThirdParty/openssl/crypto/bf \
src/ThirdParty/openssl/crypto/bio \
src/ThirdParty/openssl/crypto/blake2 \
src/ThirdParty/openssl/crypto/bn/asm \
src/ThirdParty/openssl/crypto/bn \
src/ThirdParty/openssl/crypto/buffer \
src/ThirdParty/openssl/crypto/camellia \
src/ThirdParty/openssl/crypto/cast \
src/ThirdParty/openssl/crypto/chacha \
src/ThirdParty/openssl/crypto/cmac \
src/ThirdParty/openssl/crypto/cms \
src/ThirdParty/openssl/crypto/comp \
src/ThirdParty/openssl/crypto/conf \
src/ThirdParty/openssl/crypto/ct \
src/ThirdParty/openssl/crypto/des \
src/ThirdParty/openssl/crypto/dh \
src/ThirdParty/openssl/crypto/dsa \
src/ThirdParty/openssl/crypto/dso \
src/ThirdParty/openssl/crypto/ec \
src/ThirdParty/openssl/crypto/engine \
src/ThirdParty/openssl/crypto/err \
src/ThirdParty/openssl/crypto/evp \
src/ThirdParty/openssl/crypto/hmac \
src/ThirdParty/openssl/crypto/idea \
src/ThirdParty/openssl/crypto/kdf \
src/ThirdParty/openssl/crypto/lhash \
src/ThirdParty/openssl/crypto/md2 \
src/ThirdParty/openssl/crypto/md4 \
src/ThirdParty/openssl/crypto/md5/asm \
src/ThirdParty/openssl/crypto/md5 \
src/ThirdParty/openssl/crypto/mdc2 \
src/ThirdParty/openssl/crypto/modes \
src/ThirdParty/openssl/crypto/objects \
src/ThirdParty/openssl/crypto/ocsp \
src/ThirdParty/openssl/crypto/pem \
src/ThirdParty/openssl/crypto/pkcs12 \
src/ThirdParty/openssl/crypto/pkcs7 \
src/ThirdParty/openssl/crypto/poly1305 \
src/ThirdParty/openssl/crypto/rand \
src/ThirdParty/openssl/crypto/rc2 \
src/ThirdParty/openssl/crypto/rc4 \
src/ThirdParty/openssl/crypto/rc5 \
src/ThirdParty/openssl/crypto/ripemd \
src/ThirdParty/openssl/crypto/rsa \
src/ThirdParty/openssl/crypto/seed \
src/ThirdParty/openssl/crypto/sha \
src/ThirdParty/openssl/crypto/srp \
src/ThirdParty/openssl/crypto/stack \
src/ThirdParty/openssl/crypto/ts \
src/ThirdParty/openssl/crypto/txt_db \
src/ThirdParty/openssl/crypto/ui \
src/ThirdParty/openssl/crypto/whrlpool \
src/ThirdParty/openssl/crypto/x509 \
src/ThirdParty/openssl/crypto/x509v3 \
src/ThirdParty/openssl/demos/bio \
src/ThirdParty/openssl/demos/cms \
src/ThirdParty/openssl/demos/evp \
src/ThirdParty/openssl/demos/pkcs12 \
src/ThirdParty/openssl/demos/smime \
src/ThirdParty/openssl/engines/afalg \
src/ThirdParty/openssl/engines \
src/ThirdParty/openssl/fuzz \
src/ThirdParty/openssl/ms \
src/ThirdParty/openssl/ssl \
src/ThirdParty/openssl/ssl/record \
src/ThirdParty/openssl/ssl/statem \
src/ThirdParty/openssl/test \
src/ThirdParty/poco/CppUnit/WinTestRunner/src \
src/ThirdParty/poco/CppUnit/src \
src/ThirdParty/poco/Crypto/samples/genrsakey/src \
src/ThirdParty/poco/Crypto/src \
src/ThirdParty/poco/Crypto/testsuite/src \
src/ThirdParty/poco/Data/MySQL/src \
src/ThirdParty/poco/Data/MySQL/testsuite/src \
src/ThirdParty/poco/Data/ODBC/src \
src/ThirdParty/poco/Data/ODBC/testsuite/src \
src/ThirdParty/poco/Data/SQLite/src \
src/ThirdParty/poco/Data/SQLite/testsuite/src \
src/ThirdParty/poco/Data/samples/Binding/src \
src/ThirdParty/poco/Data/samples/RecordSet/src \
src/ThirdParty/poco/Data/samples/RowFormatter/src \
src/ThirdParty/poco/Data/samples/Tuple/src \
src/ThirdParty/poco/Data/samples/TypeHandler/src \
src/ThirdParty/poco/Data/samples/WebNotifier/src \
src/ThirdParty/poco/Data/src \
src/ThirdParty/poco/Data/testsuite/src \
src/ThirdParty/poco/Foundation/samples/ActiveMethod/src \
src/ThirdParty/poco/Foundation/samples/Activity/src \
src/ThirdParty/poco/Foundation/samples/BinaryReaderWriter/src \
src/ThirdParty/poco/Foundation/samples/DateTime/src \
src/ThirdParty/poco/Foundation/samples/LineEndingConverter/src \
src/ThirdParty/poco/Foundation/samples/LogRotation/src \
src/ThirdParty/poco/Foundation/samples/Logger/src \
src/ThirdParty/poco/Foundation/samples/NotificationQueue/src \
src/ThirdParty/poco/Foundation/samples/StringTokenizer/src \
src/ThirdParty/poco/Foundation/samples/Timer/src \
src/ThirdParty/poco/Foundation/samples/URI/src \
src/ThirdParty/poco/Foundation/samples/base64decode/src \
src/ThirdParty/poco/Foundation/samples/base64encode/src \
src/ThirdParty/poco/Foundation/samples/deflate/src \
src/ThirdParty/poco/Foundation/samples/dir/src \
src/ThirdParty/poco/Foundation/samples/grep/src \
src/ThirdParty/poco/Foundation/samples/hmacmd5/src \
src/ThirdParty/poco/Foundation/samples/inflate/src \
src/ThirdParty/poco/Foundation/samples/md5/src \
src/ThirdParty/poco/Foundation/samples/uuidgen/src \
src/ThirdParty/poco/Foundation/src \
src/ThirdParty/poco/Foundation/testsuite/src \
src/ThirdParty/poco/Foundation/wcelibcex-1.0/src \
src/ThirdParty/poco/JSON/samples/Benchmark/src \
src/ThirdParty/poco/JSON/src \
src/ThirdParty/poco/JSON/testsuite/src \
src/ThirdParty/poco/MongoDB/samples/SQLToMongo/src \
src/ThirdParty/poco/MongoDB/src \
src/ThirdParty/poco/MongoDB/testsuite/src \
src/ThirdParty/poco/Net/samples/EchoServer/src \
src/ThirdParty/poco/Net/samples/HTTPFormServer/src \
src/ThirdParty/poco/Net/samples/HTTPLoadTest/src \
src/ThirdParty/poco/Net/samples/HTTPTimeServer/src \
src/ThirdParty/poco/Net/samples/Mail/src \
src/ThirdParty/poco/Net/samples/Ping/src \
src/ThirdParty/poco/Net/samples/SMTPLogger/src \
src/ThirdParty/poco/Net/samples/TimeServer/src \
src/ThirdParty/poco/Net/samples/WebSocketServer/src \
src/ThirdParty/poco/Net/samples/dict/src \
src/ThirdParty/poco/Net/samples/download/src \
src/ThirdParty/poco/Net/samples/httpget/src \
src/ThirdParty/poco/Net/samples/ifconfig/src \
src/ThirdParty/poco/Net/src \
src/ThirdParty/poco/Net/testsuite/src \
src/ThirdParty/poco/NetSSL_OpenSSL/samples/HTTPSTimeServer/src \
src/ThirdParty/poco/NetSSL_OpenSSL/samples/Mail/src \
src/ThirdParty/poco/NetSSL_OpenSSL/samples/TwitterClient/src \
src/ThirdParty/poco/NetSSL_OpenSSL/samples/download/src \
src/ThirdParty/poco/NetSSL_OpenSSL/src \
src/ThirdParty/poco/NetSSL_OpenSSL/testsuite/src \
src/ThirdParty/poco/PageCompiler/File2Page/src \
src/ThirdParty/poco/PageCompiler/samples/HTTPTimeServer/src \
src/ThirdParty/poco/PageCompiler/src \
src/ThirdParty/poco/Redis/src \
src/ThirdParty/poco/Redis/testsuite/src \
src/ThirdParty/poco/Util/samples/SampleApp/src \
src/ThirdParty/poco/Util/samples/SampleServer/src \
src/ThirdParty/poco/Util/samples/Units/src \
src/ThirdParty/poco/Util/samples/pkill/src \
src/ThirdParty/poco/Util/src \
src/ThirdParty/poco/Util/testsuite/src \
src/ThirdParty/poco/XML/samples/DOMParser/src \
src/ThirdParty/poco/XML/samples/DOMWriter/src \
src/ThirdParty/poco/XML/samples/PrettyPrint/src \
src/ThirdParty/poco/XML/samples/SAXParser/src \
src/ThirdParty/poco/XML/src \
src/ThirdParty/poco/XML/testsuite/src \
src/ThirdParty/poco/Zip/samples/unzip/src \
src/ThirdParty/poco/Zip/samples/zip/src \
src/ThirdParty/poco/Zip/src \
src/ThirdParty/poco/Zip/testsuite/src \
src/ThirdParty/poco/build/CMakeFiles/3.9.1/CompilerIdC \
src/ThirdParty/poco/build/CMakeFiles/3.9.1/CompilerIdCXX \
src/ThirdParty/poco/build/CMakeFiles \
src/ThirdParty/poco/build/script \
src/ThirdParty/poco/cmake \
src/ThirdParty/rapidjson/example/capitalize \
src/ThirdParty/rapidjson/example/condense \
src/ThirdParty/rapidjson/example/filterkey \
src/ThirdParty/rapidjson/example/filterkeydom \
src/ThirdParty/rapidjson/example/jsonx \
src/ThirdParty/rapidjson/example/lookaheadparser \
src/ThirdParty/rapidjson/example/messagereader \
src/ThirdParty/rapidjson/example/parsebyparts \
src/ThirdParty/rapidjson/example/pretty \
src/ThirdParty/rapidjson/example/prettyauto \
src/ThirdParty/rapidjson/example/schemavalidator \
src/ThirdParty/rapidjson/example/serialize \
src/ThirdParty/rapidjson/example/simpledom \
src/ThirdParty/rapidjson/example/simplepullreader \
src/ThirdParty/rapidjson/example/simplereader \
src/ThirdParty/rapidjson/example/simplewriter \
src/ThirdParty/rapidjson/example/tutorial \
src/ThirdParty/rapidjson/test/perftest \
src/ThirdParty/rapidjson/test/unittest \
src/ThirdParty/seasocks/src/app/c \
src/ThirdParty/seasocks/src/main/c \
src/ThirdParty/seasocks/src/main/c/internal \
src/ThirdParty/seasocks/src/main/c/md5 \
src/ThirdParty/seasocks/src/main/c/seasocks \
src/ThirdParty/seasocks/src/main/c/sha1 \
src/ThirdParty/seasocks/src/main/c/util \
src/ThirdParty/seasocks/src/test/c \
src/ThirdParty/websocketpp/examples/Console \
src/ThirdParty/websocketpp/examples/QT/SioChatDemo \
src/ThirdParty/websocketpp/lib/rapidjson/example/capitalize \
src/ThirdParty/websocketpp/lib/rapidjson/example/condense \
src/ThirdParty/websocketpp/lib/rapidjson/example/messagereader \
src/ThirdParty/websocketpp/lib/rapidjson/example/pretty \
src/ThirdParty/websocketpp/lib/rapidjson/example/prettyauto \
src/ThirdParty/websocketpp/lib/rapidjson/example/serialize \
src/ThirdParty/websocketpp/lib/rapidjson/example/simpledom \
src/ThirdParty/websocketpp/lib/rapidjson/example/simplereader \
src/ThirdParty/websocketpp/lib/rapidjson/example/simplewriter \
src/ThirdParty/websocketpp/lib/rapidjson/example/tutorial \
src/ThirdParty/websocketpp/lib/rapidjson/test/perftest \
src/ThirdParty/websocketpp/lib/rapidjson/test/unittest \
src/ThirdParty/websocketpp/lib/rapidjson/thirdparty/gtest/codegear \
src/ThirdParty/websocketpp/lib/rapidjson/thirdparty/gtest/samples \
src/ThirdParty/websocketpp/lib/rapidjson/thirdparty/gtest/src \
src/ThirdParty/websocketpp/lib/rapidjson/thirdparty/gtest/test \
src/ThirdParty/websocketpp/lib/rapidjson/thirdparty/gtest/xcode/Samples/FrameworkSample \
src/ThirdParty/websocketpp/lib/websocketpp/docs \
src/ThirdParty/websocketpp/lib/websocketpp/examples/associative_storage \
src/ThirdParty/websocketpp/lib/websocketpp/examples/broadcast_server \
src/ThirdParty/websocketpp/lib/websocketpp/examples/debug_client \
src/ThirdParty/websocketpp/lib/websocketpp/examples/debug_server \
src/ThirdParty/websocketpp/lib/websocketpp/examples/dev \
src/ThirdParty/websocketpp/lib/websocketpp/examples/echo_server \
src/ThirdParty/websocketpp/lib/websocketpp/examples/echo_server_both \
src/ThirdParty/websocketpp/lib/websocketpp/examples/echo_server_tls \
src/ThirdParty/websocketpp/lib/websocketpp/examples/enriched_storage \
src/ThirdParty/websocketpp/lib/websocketpp/examples/handler_switch \
src/ThirdParty/websocketpp/lib/websocketpp/examples/iostream_server \
src/ThirdParty/websocketpp/lib/websocketpp/examples/print_server \
src/ThirdParty/websocketpp/lib/websocketpp/examples/simple_broadcast_server \
src/ThirdParty/websocketpp/lib/websocketpp/examples/sip_client \
src/ThirdParty/websocketpp/lib/websocketpp/examples/subprotocol_server \
src/ThirdParty/websocketpp/lib/websocketpp/examples/telemetry_client \
src/ThirdParty/websocketpp/lib/websocketpp/examples/telemetry_server \
src/ThirdParty/websocketpp/lib/websocketpp/examples/testee_client \
src/ThirdParty/websocketpp/lib/websocketpp/examples/testee_server \
src/ThirdParty/websocketpp/lib/websocketpp/examples/utility_client \
src/ThirdParty/websocketpp/lib/websocketpp/test/connection \
src/ThirdParty/websocketpp/lib/websocketpp/test/endpoint \
src/ThirdParty/websocketpp/lib/websocketpp/test/extension \
src/ThirdParty/websocketpp/lib/websocketpp/test/http \
src/ThirdParty/websocketpp/lib/websocketpp/test/logger \
src/ThirdParty/websocketpp/lib/websocketpp/test/message_buffer \
src/ThirdParty/websocketpp/lib/websocketpp/test/processors \
src/ThirdParty/websocketpp/lib/websocketpp/test/random \
src/ThirdParty/websocketpp/lib/websocketpp/test/roles \
src/ThirdParty/websocketpp/lib/websocketpp/test/transport/asio \
src/ThirdParty/websocketpp/lib/websocketpp/test/transport \
src/ThirdParty/websocketpp/lib/websocketpp/test/transport/iostream \
src/ThirdParty/websocketpp/lib/websocketpp/test/utility \
src/ThirdParty/websocketpp/lib/websocketpp/tutorials/utility_client \
src/ThirdParty/websocketpp/src/internal \
src/ThirdParty/websocketpp/src \
src/ThirdParty/websocketpp/test \
src/ThirdParty/yaml-cpp/src \
src/ThirdParty/yaml-cpp/src/contrib \
src/ThirdParty/yaml-cpp/test/gmock-1.7.0/fused-src \
src/ThirdParty/yaml-cpp/test/gmock-1.7.0/gtest/codegear \
src/ThirdParty/yaml-cpp/test/gmock-1.7.0/gtest/fused-src/gtest \
src/ThirdParty/yaml-cpp/test/gmock-1.7.0/gtest/samples \
src/ThirdParty/yaml-cpp/test/gmock-1.7.0/gtest/src \
src/ThirdParty/yaml-cpp/test/gmock-1.7.0/gtest/test \
src/ThirdParty/yaml-cpp/test/gmock-1.7.0/gtest/xcode/Samples/FrameworkSample \
src/ThirdParty/yaml-cpp/test/gmock-1.7.0/src \
src/ThirdParty/yaml-cpp/test/gmock-1.7.0/test \
src/ThirdParty/yaml-cpp/test/integration \
src/ThirdParty/yaml-cpp/test \
src/ThirdParty/yaml-cpp/test/node \
src/ThirdParty/yaml-cpp/util \
src/ThirdParty/zeromq/CMakeFiles/3.10.2/CompilerIdC \
src/ThirdParty/zeromq/CMakeFiles/3.10.2/CompilerIdCXX \
src/ThirdParty/zeromq/CMakeFiles/CheckTypeSize \
src/ThirdParty/zeromq/CMakeFiles \
src/ThirdParty/zeromq/build/CMakeFiles/3.10.2/CompilerIdC \
src/ThirdParty/zeromq/build/CMakeFiles/3.10.2/CompilerIdCXX \
src/ThirdParty/zeromq/build/CMakeFiles/CheckTypeSize \
src/ThirdParty/zeromq/build/CMakeFiles \
src/ThirdParty/zeromq/builds/msvc \
src/ThirdParty/zeromq/builds/zos \
src/ThirdParty/zeromq/perf \
src/ThirdParty/zeromq/src \
src/ThirdParty/zeromq/tests \
src/ThirdParty/zeromq/tools \
src/ThirdParty/zeromq/tweetnacl/contrib/randombytes \
src/ThirdParty/zeromq/tweetnacl/src \

